name: Test Action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  TEST1: ${{ github.repository }}
  TEST2: ${{ github.event.repository.name }}

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Repository Name
        run: |
          REPO_NAME=${{ github.repository }}
          REPO_NAME=${REPO_NAME#*/}
          echo "Repository Name: $REPO_NAME"
      - name: Step1
        run: |
          echo ${{ env.TEST1 }}
          echo ${{ env.TEST2 }}
          echo ${{ github.repository_name }}
          echo $REPO_NAME
